// GENERATED by scripts/extract-tokens.mjs — do not edit by hand.
// Source:   ~/Documents/GitHub/library-design-system
// Revision: b5b6fd52f · 2026-08-31 · main
// Re-run `npm run tokens` after the design system changes, then `npm run build`.

import type { TokenTable } from "./tokens.ts";

export const TOKENS: TokenTable = {
	"themes": [
		"custom-light",
		"empeo-dark",
		"empeo-light",
		"etaxgo-light",
		"salesbear-light",
		"venio-dark",
		"venio-light"
	],
	"rows": [
		{
			"key": "background-default",
			"cssVar": "--go5-background-default",
			"cls": null,
			"group": "other",
			"values": {
				"custom-light": "#F5F5F5",
				"empeo-dark": "#383842",
				"empeo-light": "#ECECF1",
				"etaxgo-light": "#ECECF1",
				"salesbear-light": "#F5F5F5",
				"venio-dark": "#383842",
				"venio-light": "#ECECF1"
			}
		},
		{
			"key": "background-light",
			"cssVar": "--go5-background-light",
			"cls": null,
			"group": "other",
			"values": {
				"custom-light": "#FFFFFF",
				"empeo-dark": "#1C1C22",
				"empeo-light": "#FFFFFF",
				"etaxgo-light": "#FFFFFF",
				"salesbear-light": "#FFFFFF",
				"venio-dark": "#1C1C22",
				"venio-light": "#FFFFFF"
			}
		},
		{
			"key": "badge-secondary-bg",
			"cssVar": "--go5-badge-secondary-bg",
			"cls": null,
			"group": "other",
			"values": {
				"custom-light": "#F6F6F8",
				"empeo-dark": "#525260",
				"empeo-light": "#ECECF1",
				"etaxgo-light": "#ECECF1",
				"salesbear-light": "#F6F6F8",
				"venio-dark": "#525260",
				"venio-light": "#ECECF1"
			}
		},
		{
			"key": "badge-secondary-text",
			"cssVar": "--go5-badge-secondary-text",
			"cls": null,
			"group": "other",
			"values": {
				"custom-light": "#A5A5B6",
				"empeo-dark": "#BCBCC8",
				"empeo-light": "#A5A5B6",
				"etaxgo-light": "#A5A5B6",
				"salesbear-light": "#A5A5B6",
				"venio-dark": "#BCBCC8",
				"venio-light": "#A5A5B6"
			}
		},
		{
			"key": "bg-primary",
			"cssVar": "--go5-bg-primary",
			"cls": null,
			"group": "surface",
			"values": {
				"custom-light": "#FFFFFF",
				"empeo-dark": "#1C1C22",
				"empeo-light": "#FFFFFF",
				"etaxgo-light": "#FFFFFF",
				"salesbear-light": "#FFFFFF",
				"venio-dark": "#1C1C22",
				"venio-light": "#FFFFFF"
			}
		},
		{
			"key": "bg-secondary",
			"cssVar": "--go5-bg-secondary",
			"cls": null,
			"group": "surface",
			"values": {
				"custom-light": "#F6F6F8",
				"empeo-dark": "#383842",
				"empeo-light": "#F6F6F8",
				"etaxgo-light": "#F6F6F8",
				"salesbear-light": "#F6F6F8",
				"venio-dark": "#383842",
				"venio-light": "#F6F6F8"
			}
		},
		{
			"key": "button-outline-default-bg",
			"cssVar": "--go5-button-outline-default-bg",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#FFFFFF",
				"empeo-dark": "#1C1C22",
				"empeo-light": "#FFFFFF",
				"etaxgo-light": "#FFFFFF",
				"salesbear-light": "#FFFFFF",
				"venio-dark": "#1C1C22",
				"venio-light": "#FFFFFF"
			}
		},
		{
			"key": "button-outline-default-line",
			"cssVar": "--go5-button-outline-default-line",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#D2D2DA",
				"empeo-dark": "#838395",
				"empeo-light": "#D2D2DA",
				"etaxgo-light": "#D2D2DA",
				"salesbear-light": "#DFDFE8",
				"venio-dark": "#838395",
				"venio-light": "#DFDFE8"
			}
		},
		{
			"key": "button-outline-default-text",
			"cssVar": "--go5-button-outline-default-text",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#525260",
				"empeo-dark": "#F6F6F8",
				"empeo-light": "#383842",
				"etaxgo-light": "#383842",
				"salesbear-light": "#525260",
				"venio-dark": "#F6F6F8",
				"venio-light": "#525260"
			}
		},
		{
			"key": "button-outline-disabled-bg",
			"cssVar": "--go5-button-outline-disabled-bg",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#FFFFFF",
				"empeo-dark": "#1C1C22",
				"empeo-light": "#FFFFFF",
				"etaxgo-light": "#FFFFFF",
				"salesbear-light": "#FFFFFF",
				"venio-dark": "#1C1C22",
				"venio-light": "#FFFFFF"
			}
		},
		{
			"key": "button-outline-disabled-line",
			"cssVar": "--go5-button-outline-disabled-line",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#E2E2E2",
				"empeo-dark": "#6A6A7C",
				"empeo-light": "#DFDFE8",
				"etaxgo-light": "#E2E2E2",
				"salesbear-light": "#E2E2E2",
				"venio-dark": "#6A6A7C",
				"venio-light": "#E2E2E2"
			}
		},
		{
			"key": "button-outline-disabled-text",
			"cssVar": "--go5-button-outline-disabled-text",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#D2D2DA",
				"empeo-dark": "#838395",
				"empeo-light": "#D2D2DA",
				"etaxgo-light": "#D2D2DA",
				"salesbear-light": "#D2D2DA",
				"venio-dark": "#838395",
				"venio-light": "#D2D2DA"
			}
		},
		{
			"key": "button-outline-hover-bg",
			"cssVar": "--go5-button-outline-hover-bg",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#F5F9FF",
				"empeo-dark": "#F05B2F1A",
				"empeo-light": "#FFF3EC",
				"etaxgo-light": "#FFEAE5",
				"salesbear-light": "#FFF8E0",
				"venio-dark": "rgba(from var(--go5-text-color-2) r g b / 0.6)",
				"venio-light": "#F5F9FF"
			}
		},
		{
			"key": "button-outline-hover-line",
			"cssVar": "--go5-button-outline-hover-line",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#116DFC",
				"empeo-dark": "#F05B2F",
				"empeo-light": "#F05B2F",
				"etaxgo-light": "#EB1C26",
				"salesbear-light": "#FFC505",
				"venio-dark": "#116DFC",
				"venio-light": "#116DFC"
			}
		},
		{
			"key": "button-outline-hover-text",
			"cssVar": "--go5-button-outline-hover-text",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#116DFC",
				"empeo-dark": "#F05B2F",
				"empeo-light": "#F05B2F",
				"etaxgo-light": "#EB1C26",
				"salesbear-light": "#FFC505",
				"venio-dark": "#116DFC",
				"venio-light": "#116DFC"
			}
		},
		{
			"key": "button-outline-pressed-bg",
			"cssVar": "--go5-button-outline-pressed-bg",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#E7F0FF",
				"empeo-dark": "#FFE1CC",
				"empeo-light": "#FFE1CC",
				"etaxgo-light": "#FFBEB2",
				"salesbear-light": "#FFEAA3",
				"venio-dark": "#051F47",
				"venio-light": "#E7F0FF"
			}
		},
		{
			"key": "button-outline-pressed-line",
			"cssVar": "--go5-button-outline-pressed-line",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#116DFC",
				"empeo-dark": "#F05B2F",
				"empeo-light": "#F05B2F",
				"etaxgo-light": "#EB1C26",
				"salesbear-light": "#FFC505",
				"venio-dark": "#116DFC",
				"venio-light": "#116DFC"
			}
		},
		{
			"key": "button-outline-pressed-text",
			"cssVar": "--go5-button-outline-pressed-text",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#116DFC",
				"empeo-dark": "#F05B2F",
				"empeo-light": "#F05B2F",
				"etaxgo-light": "#EB1C26",
				"salesbear-light": "#FFC505",
				"venio-dark": "#116DFC",
				"venio-light": "#116DFC"
			}
		},
		{
			"key": "button-primary-default-bg",
			"cssVar": "--go5-button-primary-default-bg",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#116DFC",
				"empeo-dark": "#F05B2F",
				"empeo-light": "#F05B2F",
				"etaxgo-light": "#EB1C26",
				"salesbear-light": "#FFC505",
				"venio-dark": "#116DFC",
				"venio-light": "#116DFC"
			}
		},
		{
			"key": "button-primary-default-line",
			"cssVar": "--go5-button-primary-default-line",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#116DFC",
				"empeo-dark": "#F05B2F",
				"empeo-light": "#F05B2F",
				"etaxgo-light": "#EB1C26",
				"salesbear-light": "#FFC505",
				"venio-dark": "#116DFC",
				"venio-light": "#116DFC"
			}
		},
		{
			"key": "button-primary-default-text",
			"cssVar": "--go5-button-primary-default-text",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#FFFFFF",
				"empeo-dark": "#FFFFFF",
				"empeo-light": "#FFFFFF",
				"etaxgo-light": "#FFFFFF",
				"salesbear-light": "#FFFFFF",
				"venio-dark": "#FFFFFF",
				"venio-light": "#FFFFFF"
			}
		},
		{
			"key": "button-primary-disabled-bg",
			"cssVar": "--go5-button-primary-disabled-bg",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#F5F5F5",
				"empeo-dark": "#525260",
				"empeo-light": "#ECECF1",
				"etaxgo-light": "#ECECF1",
				"salesbear-light": "#F5F5F5",
				"venio-dark": "#525260",
				"venio-light": "#F5F5F5"
			}
		},
		{
			"key": "button-primary-disabled-line",
			"cssVar": "--go5-button-primary-disabled-line",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#F5F5F5",
				"empeo-dark": "#525260",
				"empeo-light": "#ECECF1",
				"etaxgo-light": "#ECECF1",
				"salesbear-light": "#F5F5F5",
				"venio-dark": "#525260",
				"venio-light": "#F5F5F5"
			}
		},
		{
			"key": "button-primary-disabled-text",
			"cssVar": "--go5-button-primary-disabled-text",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#D2D2DA",
				"empeo-dark": "#A5A5B6",
				"empeo-light": "#BCBCC8",
				"etaxgo-light": "#BCBCC8",
				"salesbear-light": "#D2D2DA",
				"venio-dark": "#A5A5B6",
				"venio-light": "#D2D2DA"
			}
		},
		{
			"key": "button-primary-hover-bg",
			"cssVar": "--go5-button-primary-hover-bg",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#418AFD",
				"empeo-dark": "#F26C44",
				"empeo-light": "#F26C44",
				"etaxgo-light": "#F96252",
				"salesbear-light": "#FFDC66",
				"venio-dark": "#418AFD",
				"venio-light": "#418AFD"
			}
		},
		{
			"key": "button-primary-hover-line",
			"cssVar": "--go5-button-primary-hover-line",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#418AFD",
				"empeo-dark": "#F26C44",
				"empeo-light": "#F26C44",
				"etaxgo-light": "#F96252",
				"salesbear-light": "#FFDC66",
				"venio-dark": "#418AFD",
				"venio-light": "#418AFD"
			}
		},
		{
			"key": "button-primary-hover-text",
			"cssVar": "--go5-button-primary-hover-text",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#FFFFFF",
				"empeo-dark": "#FFFFFF",
				"empeo-light": "#FFFFFF",
				"etaxgo-light": "#FFFFFF",
				"salesbear-light": "#FFFFFF",
				"venio-dark": "#FFFFFF",
				"venio-light": "#FFFFFF"
			}
		},
		{
			"key": "button-primary-pressed-bg",
			"cssVar": "--go5-button-primary-pressed-bg",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#035CE6",
				"empeo-dark": "#E54111",
				"empeo-light": "#E54111",
				"etaxgo-light": "#C71F22",
				"salesbear-light": "#FFB700",
				"venio-dark": "#035CE6",
				"venio-light": "#035CE6"
			}
		},
		{
			"key": "button-primary-pressed-line",
			"cssVar": "--go5-button-primary-pressed-line",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#035CE6",
				"empeo-dark": "#E54111",
				"empeo-light": "#E54111",
				"etaxgo-light": "#C71F22",
				"salesbear-light": "#FFB700",
				"venio-dark": "#035CE6",
				"venio-light": "#035CE6"
			}
		},
		{
			"key": "button-primary-pressed-text",
			"cssVar": "--go5-button-primary-pressed-text",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#FFFFFF",
				"empeo-dark": "#FFFFFF",
				"empeo-light": "#FFFFFF",
				"etaxgo-light": "#FFFFFF",
				"salesbear-light": "#FFFFFF",
				"venio-dark": "#FFFFFF",
				"venio-light": "#FFFFFF"
			}
		},
		{
			"key": "button-secondary-default-bg",
			"cssVar": "--go5-button-secondary-default-bg",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#FFFFFF",
				"empeo-dark": "#1C1C22",
				"empeo-light": "#FFFFFF",
				"etaxgo-light": "#FFFFFF",
				"salesbear-light": "#FFFFFF",
				"venio-dark": "#1C1C22",
				"venio-light": "#FFFFFF"
			}
		},
		{
			"key": "button-secondary-default-line",
			"cssVar": "--go5-button-secondary-default-line",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#D2D2DA",
				"empeo-dark": "#6A6A7C",
				"empeo-light": "#DFDFE8",
				"etaxgo-light": "#D2D2DA",
				"salesbear-light": "#DFDFE8",
				"venio-dark": "#6A6A7C",
				"venio-light": "#DFDFE8"
			}
		},
		{
			"key": "button-secondary-default-text",
			"cssVar": "--go5-button-secondary-default-text",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#525260",
				"empeo-dark": "#ECECF1",
				"empeo-light": "#525260",
				"etaxgo-light": "#525260",
				"salesbear-light": "#525260",
				"venio-dark": "#ECECF1",
				"venio-light": "#525260"
			}
		},
		{
			"key": "button-secondary-disabled-bg",
			"cssVar": "--go5-button-secondary-disabled-bg",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#FFFFFF",
				"empeo-dark": "#1C1C22",
				"empeo-light": "#FFFFFF",
				"etaxgo-light": "#FFFFFF",
				"salesbear-light": "#FFFFFF",
				"venio-dark": "#1C1C22",
				"venio-light": "#FFFFFF"
			}
		},
		{
			"key": "button-secondary-disabled-line",
			"cssVar": "--go5-button-secondary-disabled-line",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#E2E2E2",
				"empeo-dark": "#6A6A7C",
				"empeo-light": "#DFDFE8",
				"etaxgo-light": "#E2E2E2",
				"salesbear-light": "#E2E2E2",
				"venio-dark": "#6A6A7C",
				"venio-light": "#DFDFE8"
			}
		},
		{
			"key": "button-secondary-disabled-text",
			"cssVar": "--go5-button-secondary-disabled-text",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#D2D2DA",
				"empeo-dark": "#838395",
				"empeo-light": "#D2D2DA",
				"etaxgo-light": "#D2D2DA",
				"salesbear-light": "#D2D2DA",
				"venio-dark": "#838395",
				"venio-light": "#D2D2DA"
			}
		},
		{
			"key": "button-secondary-hover-bg",
			"cssVar": "--go5-button-secondary-hover-bg",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#F6F6F8",
				"empeo-dark": "#383842",
				"empeo-light": "#F6F6F8",
				"etaxgo-light": "#F6F6F8",
				"salesbear-light": "#F6F6F8",
				"venio-dark": "#383842",
				"venio-light": "#F6F6F8"
			}
		},
		{
			"key": "button-secondary-hover-line",
			"cssVar": "--go5-button-secondary-hover-line",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#D2D2DA",
				"empeo-dark": "#D9D9D9",
				"empeo-light": "#D9D9D9",
				"etaxgo-light": "#D2D2DA",
				"salesbear-light": "#DFDFE8",
				"venio-dark": "#D9D9D9",
				"venio-light": "#DFDFE8"
			}
		},
		{
			"key": "button-secondary-hover-text",
			"cssVar": "--go5-button-secondary-hover-text",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#525260",
				"empeo-dark": "#ECECF1",
				"empeo-light": "#525260",
				"etaxgo-light": "#525260",
				"salesbear-light": "#525260",
				"venio-dark": "#ECECF1",
				"venio-light": "#525260"
			}
		},
		{
			"key": "button-secondary-pressed-bg",
			"cssVar": "--go5-button-secondary-pressed-bg",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "rgba(226, 226, 226, 0.6)",
				"empeo-dark": "#525260",
				"empeo-light": "#ECECF1",
				"etaxgo-light": "#ECECF1",
				"salesbear-light": "rgba(226, 226, 226, 0.6)",
				"venio-dark": "#525260",
				"venio-light": "rgba(226, 226, 226, 0.6)"
			}
		},
		{
			"key": "button-secondary-pressed-line",
			"cssVar": "--go5-button-secondary-pressed-line",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#D2D2DA",
				"empeo-dark": "#D9D9D9",
				"empeo-light": "#D9D9D9",
				"etaxgo-light": "#D2D2DA",
				"salesbear-light": "#DFDFE8",
				"venio-dark": "#D9D9D9",
				"venio-light": "#DFDFE8"
			}
		},
		{
			"key": "button-secondary-pressed-text",
			"cssVar": "--go5-button-secondary-pressed-text",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#525260",
				"empeo-dark": "#ECECF1",
				"empeo-light": "#525260",
				"etaxgo-light": "#525260",
				"salesbear-light": "#525260",
				"venio-dark": "#ECECF1",
				"venio-light": "#525260"
			}
		},
		{
			"key": "button-text-default-bg",
			"cssVar": "--go5-button-text-default-bg",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "transparent",
				"empeo-dark": "transparent",
				"empeo-light": "transparent",
				"etaxgo-light": "transparent",
				"salesbear-light": "transparent",
				"venio-dark": "transparent",
				"venio-light": "transparent"
			}
		},
		{
			"key": "button-text-default-line",
			"cssVar": "--go5-button-text-default-line",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "transparent",
				"empeo-dark": "transparent",
				"empeo-light": "transparent",
				"etaxgo-light": "transparent",
				"salesbear-light": "transparent",
				"venio-dark": "transparent",
				"venio-light": "transparent"
			}
		},
		{
			"key": "button-text-default-text",
			"cssVar": "--go5-button-text-default-text",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#116DFC",
				"empeo-dark": "#F05B2F",
				"empeo-light": "#F05B2F",
				"etaxgo-light": "#EB1C26",
				"salesbear-light": "#FFC505",
				"venio-dark": "#116DFC",
				"venio-light": "#116DFC"
			}
		},
		{
			"key": "button-text-disabled-bg",
			"cssVar": "--go5-button-text-disabled-bg",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "transparent",
				"empeo-dark": "transparent",
				"empeo-light": "transparent",
				"etaxgo-light": "transparent",
				"salesbear-light": "transparent",
				"venio-dark": "transparent",
				"venio-light": "transparent"
			}
		},
		{
			"key": "button-text-disabled-line",
			"cssVar": "--go5-button-text-disabled-line",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "transparent",
				"empeo-dark": "transparent",
				"empeo-light": "transparent",
				"etaxgo-light": "transparent",
				"salesbear-light": "transparent",
				"venio-dark": "transparent",
				"venio-light": "transparent"
			}
		},
		{
			"key": "button-text-disabled-text",
			"cssVar": "--go5-button-text-disabled-text",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#D2D2DA",
				"empeo-dark": "#A5A5B6",
				"empeo-light": "#BCBCC8",
				"etaxgo-light": "#D2D2DA",
				"salesbear-light": "#D2D2DA",
				"venio-dark": "#A5A5B6",
				"venio-light": "#D2D2DA"
			}
		},
		{
			"key": "button-text-hover-bg",
			"cssVar": "--go5-button-text-hover-bg",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "transparent",
				"empeo-dark": "transparent",
				"empeo-light": "transparent",
				"etaxgo-light": "transparent",
				"salesbear-light": "transparent",
				"venio-dark": "transparent",
				"venio-light": "transparent"
			}
		},
		{
			"key": "button-text-hover-line",
			"cssVar": "--go5-button-text-hover-line",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "transparent",
				"empeo-dark": "transparent",
				"empeo-light": "transparent",
				"etaxgo-light": "transparent",
				"salesbear-light": "transparent",
				"venio-dark": "transparent",
				"venio-light": "transparent"
			}
		},
		{
			"key": "button-text-hover-text",
			"cssVar": "--go5-button-text-hover-text",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#418AFD",
				"empeo-dark": "#F26C44",
				"empeo-light": "#F26C44",
				"etaxgo-light": "#F96252",
				"salesbear-light": "#FFDC66",
				"venio-dark": "#418AFD",
				"venio-light": "#418AFD"
			}
		},
		{
			"key": "button-text-pressed-bg",
			"cssVar": "--go5-button-text-pressed-bg",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "transparent",
				"empeo-dark": "transparent",
				"empeo-light": "transparent",
				"etaxgo-light": "transparent",
				"salesbear-light": "transparent",
				"venio-dark": "transparent",
				"venio-light": "transparent"
			}
		},
		{
			"key": "button-text-pressed-line",
			"cssVar": "--go5-button-text-pressed-line",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "transparent",
				"empeo-dark": "transparent",
				"empeo-light": "transparent",
				"etaxgo-light": "transparent",
				"salesbear-light": "transparent",
				"venio-dark": "transparent",
				"venio-light": "transparent"
			}
		},
		{
			"key": "button-text-pressed-text",
			"cssVar": "--go5-button-text-pressed-text",
			"cls": null,
			"group": "button",
			"values": {
				"custom-light": "#035CE6",
				"empeo-dark": "#E54111",
				"empeo-light": "#E54111",
				"etaxgo-light": "#C71F22",
				"salesbear-light": "#FFB700",
				"venio-dark": "#035CE6",
				"venio-light": "#035CE6"
			}
		},
		{
			"key": "card-bg-color",
			"cssVar": "--go5-card-bg-color",
			"cls": null,
			"group": "other",
			"values": {
				"empeo-dark": "#383842",
				"empeo-light": "#FFFFFF",
				"etaxgo-light": "#FFFFFF",
				"salesbear-light": "#FFFFFF",
				"venio-dark": "#383842",
				"venio-light": "#FFFFFF"
			}
		},
		{
			"key": "card-hover",
			"cssVar": "--go5-card-hover",
			"cls": null,
			"group": "other",
			"values": {
				"empeo-dark": "rgba(255, 255, 255, 0.16)",
				"empeo-light": "rgba(0, 0, 0, 0.16)",
				"etaxgo-light": "rgba(0, 0, 0, 0.16)",
				"salesbear-light": "rgba(0, 0, 0, 0.16)",
				"venio-dark": "rgba(255, 255, 255, 0.16)",
				"venio-light": "rgba(0, 0, 0, 0.16)"
			}
		},
		{
			"key": "card-shadow",
			"cssVar": "--go5-card-shadow",
			"cls": null,
			"group": "other",
			"values": {
				"empeo-dark": "rgba(255, 255, 255, 0.08)",
				"empeo-light": "rgba(0, 0, 0, 0.08)",
				"etaxgo-light": "rgba(0, 0, 0, 0.08)",
				"salesbear-light": "rgba(0, 0, 0, 0.08)",
				"venio-dark": "rgba(255, 255, 255, 0.08)",
				"venio-light": "rgba(0, 0, 0, 0.08)"
			}
		},
		{
			"key": "color-error",
			"cssVar": "--go5-color-error",
			"cls": "go5-color-error",
			"group": "semantic",
			"values": {
				"custom-light": "#DE3A45",
				"empeo-dark": "#C81720",
				"empeo-light": "#C81720",
				"etaxgo-light": "#C81720",
				"salesbear-light": "#DE3A45",
				"venio-dark": "#FF3B30",
				"venio-light": "#DE3A45"
			}
		},
		{
			"key": "color-loading",
			"cssVar": "--go5-color-loading",
			"cls": null,
			"group": "semantic",
			"values": {
				"custom-light": "#418AFD",
				"empeo-dark": "#F26C44",
				"empeo-light": "#F26C44",
				"etaxgo-light": "#F96252",
				"salesbear-light": "#FFDC66",
				"venio-dark": "#418AFD",
				"venio-light": "#418AFD"
			}
		},
		{
			"key": "color-primary",
			"cssVar": "--go5-color-primary",
			"cls": "go5-color-primary",
			"group": "semantic",
			"values": {
				"custom-light": "#116DFC",
				"empeo-dark": "#F05B2F",
				"empeo-light": "#F05B2F",
				"etaxgo-light": "#EB1C26",
				"salesbear-light": "#FFC505",
				"venio-dark": "#116DFC",
				"venio-light": "#116DFC"
			}
		},
		{
			"key": "color-primary-dark",
			"cssVar": "--go5-color-primary-dark",
			"cls": null,
			"group": "semantic",
			"values": {
				"custom-light": "#035CE6",
				"empeo-dark": "#E54111",
				"empeo-light": "#E54111",
				"etaxgo-light": "#C71F22",
				"salesbear-light": "#FFB700",
				"venio-dark": "#035CE6",
				"venio-light": "#035CE6"
			}
		},
		{
			"key": "color-secondary",
			"cssVar": "--go5-color-secondary",
			"cls": "go5-color-secondary",
			"group": "semantic",
			"values": {
				"custom-light": "#F5F9FF",
				"empeo-dark": "#F05B2F1A",
				"empeo-light": "#FFF3EC",
				"etaxgo-light": "#FFEAE5",
				"salesbear-light": "#FFF8E0",
				"venio-dark": "#1A2641",
				"venio-light": "#F5F9FF"
			}
		},
		{
			"key": "color-success",
			"cssVar": "--go5-color-success",
			"cls": "go5-color-success",
			"group": "semantic",
			"values": {
				"custom-light": "#21CE9B",
				"empeo-dark": "#00C291",
				"empeo-light": "#00C291",
				"etaxgo-light": "#16BC6D",
				"salesbear-light": "#21CE9B",
				"venio-dark": "#21CE9B",
				"venio-light": "#21CE9B"
			}
		},
		{
			"key": "color-warning",
			"cssVar": "--go5-color-warning",
			"cls": null,
			"group": "semantic",
			"values": {
				"custom-light": "#EFC439",
				"empeo-dark": "#FFB31A",
				"empeo-light": "#FFB31A",
				"etaxgo-light": "#FFB31A",
				"salesbear-light": "#FFB700",
				"venio-dark": "#FFB31A",
				"venio-light": "#EFC439"
			}
		},
		{
			"key": "hover-bg-table",
			"cssVar": "--go5-hover-bg-table",
			"cls": null,
			"group": "other",
			"values": {
				"empeo-dark": "#2D2D36",
				"empeo-light": "#FAFAFB",
				"venio-dark": "#2D2D36",
				"venio-light": "#FAFAFB"
			}
		},
		{
			"key": "input-bg",
			"cssVar": "--go5-input-bg",
			"cls": null,
			"group": "input",
			"values": {
				"custom-light": "#FFFFFF",
				"empeo-dark": "#1C1C22",
				"empeo-light": "#FFFFFF",
				"etaxgo-light": "#FFFFFF",
				"salesbear-light": "#FFFFFF",
				"venio-dark": "#1C1C22",
				"venio-light": "#FFFFFF"
			}
		},
		{
			"key": "input-disabled-bg",
			"cssVar": "--go5-input-disabled-bg",
			"cls": null,
			"group": "input",
			"values": {
				"custom-light": "#F6F6F8",
				"empeo-dark": "#383842",
				"empeo-light": "#F6F6F8",
				"etaxgo-light": "#F6F6F8",
				"salesbear-light": "#F6F6F8",
				"venio-dark": "#383842",
				"venio-light": "#F6F6F8"
			}
		},
		{
			"key": "input-disabled-text",
			"cssVar": "--go5-input-disabled-text",
			"cls": null,
			"group": "input",
			"values": {
				"custom-light": "#D2D2DA",
				"empeo-dark": "#FFFFFF",
				"empeo-light": "#1C1C22",
				"etaxgo-light": "#D2D2DA",
				"salesbear-light": "#D2D2DA",
				"venio-dark": "#838395",
				"venio-light": "#D2D2DA"
			}
		},
		{
			"key": "input-icon",
			"cssVar": "--go5-input-icon",
			"cls": null,
			"group": "input",
			"values": {
				"custom-light": "#BCBCC8",
				"empeo-dark": "#A5A5B6",
				"empeo-light": "#BCBCC8",
				"etaxgo-light": "#BCBCC8",
				"salesbear-light": "#BCBCC8",
				"venio-dark": "#A5A5B6",
				"venio-light": "#BCBCC8"
			}
		},
		{
			"key": "input-label",
			"cssVar": "--go5-input-label",
			"cls": null,
			"group": "input",
			"values": {
				"custom-light": "#838395",
				"empeo-dark": "#D2D2DA",
				"empeo-light": "#838395",
				"etaxgo-light": "#838395",
				"salesbear-light": "#838395",
				"venio-dark": "#D2D2DA",
				"venio-light": "#838395"
			}
		},
		{
			"key": "input-line",
			"cssVar": "--go5-input-line",
			"cls": null,
			"group": "input",
			"values": {
				"custom-light": "#D2D2DA",
				"empeo-dark": "#838395",
				"empeo-light": "#D2D2DA",
				"etaxgo-light": "#D2D2DA",
				"salesbear-light": "#D2D2DA",
				"venio-dark": "#838395",
				"venio-light": "#D2D2DA"
			}
		},
		{
			"key": "input-placeholder",
			"cssVar": "--go5-input-placeholder",
			"cls": null,
			"group": "input",
			"values": {
				"custom-light": "#D2D2DA",
				"empeo-dark": "#838395",
				"empeo-light": "#D2D2DA",
				"etaxgo-light": "#D2D2DA",
				"salesbear-light": "#D2D2DA",
				"venio-dark": "#838395",
				"venio-light": "#D2D2DA"
			}
		},
		{
			"key": "input-tertiary-bg",
			"cssVar": "--go5-input-tertiary-bg",
			"cls": null,
			"group": "input",
			"values": {
				"custom-light": "#FFF8E0",
				"empeo-dark": "#FFF8E0",
				"empeo-light": "#FFF8E0",
				"etaxgo-light": "#FFF8E0",
				"salesbear-light": "#FFF8E0",
				"venio-dark": "#FFF8E0",
				"venio-light": "#FFF8E0"
			}
		},
		{
			"key": "input-tertiary-icon",
			"cssVar": "--go5-input-tertiary-icon",
			"cls": null,
			"group": "input",
			"values": {
				"custom-light": "#F8CA51",
				"empeo-dark": "#F8CA51",
				"empeo-light": "#F8CA51",
				"etaxgo-light": "#F8CA51",
				"salesbear-light": "#F8CA51",
				"venio-dark": "#F8CA51",
				"venio-light": "#F8CA51"
			}
		},
		{
			"key": "input-tertiary-line",
			"cssVar": "--go5-input-tertiary-line",
			"cls": null,
			"group": "input",
			"values": {
				"custom-light": "#FFDC66",
				"empeo-dark": "#FFDC66",
				"empeo-light": "#FFDC66",
				"etaxgo-light": "#FFDC66",
				"salesbear-light": "#FFDC66",
				"venio-dark": "#FFDC66",
				"venio-light": "#FFDC66"
			}
		},
		{
			"key": "input-tertiary-text",
			"cssVar": "--go5-input-tertiary-text",
			"cls": null,
			"group": "input",
			"values": {
				"custom-light": "#1A1A1A",
				"empeo-dark": "#1A1A1A",
				"empeo-light": "#1A1A1A",
				"etaxgo-light": "#1A1A1A",
				"salesbear-light": "#1A1A1A",
				"venio-dark": "#1A1A1A",
				"venio-light": "#1A1A1A"
			}
		},
		{
			"key": "input-text",
			"cssVar": "--go5-input-text",
			"cls": null,
			"group": "input",
			"values": {
				"custom-light": "#1C1C22",
				"empeo-dark": "#FFFFFF",
				"empeo-light": "#1C1C22",
				"etaxgo-light": "#1C1C22",
				"salesbear-light": "#1C1C22",
				"venio-dark": "#FFFFFF",
				"venio-light": "#1C1C22"
			}
		},
		{
			"key": "nav-background",
			"cssVar": "--go5-nav-background",
			"cls": null,
			"group": "other",
			"values": {
				"custom-light": "linear-gradient(180deg, #0581F6 0%, #0FB3E6 68.75%)",
				"empeo-dark": "linear-gradient(180deg, #F47243 9.18%, #E54111 71.62%)",
				"empeo-light": "linear-gradient(180deg, #F47243 9.18%, #E54111 71.62%)",
				"etaxgo-light": "linear-gradient(180deg, #C71F22 9.18%, #EB1C26 71.62%)",
				"salesbear-light": "#FFFFFF",
				"venio-dark": "linear-gradient(180deg, #0581F6 0%, #0FB3E6 68.75%)",
				"venio-light": "linear-gradient(180deg, #0581F6 0%, #0FB3E6 68.75%)"
			}
		},
		{
			"key": "nav-bg-icon-active",
			"cssVar": "--go5-nav-bg-icon-active",
			"cls": null,
			"group": "other",
			"values": {
				"custom-light": "rgb(26 26 26 / 20%)",
				"empeo-dark": "rgb(255 255 255 / 30%)",
				"empeo-light": "rgb(255 255 255 / 30%)",
				"etaxgo-light": "rgb(255 255 255 / 30%)",
				"salesbear-light": "#FFF3CC",
				"venio-dark": "rgb(255 255 255 / 30%)",
				"venio-light": "rgb(26 26 26 / 20%)"
			}
		},
		{
			"key": "nav-box-shadow",
			"cssVar": "--go5-nav-box-shadow",
			"cls": null,
			"group": "other",
			"values": {
				"salesbear-light": "drop-shadow(0px 0px 10px rgba(202, 202, 202, 0.5))"
			}
		},
		{
			"key": "nav-icon-active",
			"cssVar": "--go5-nav-icon-active",
			"cls": null,
			"group": "other",
			"values": {
				"custom-light": "#FFFFFF",
				"empeo-dark": "#1C1C22",
				"empeo-light": "#FFFFFF",
				"etaxgo-light": "#FFFFFF",
				"salesbear-light": "#FFC505",
				"venio-dark": "#1C1C22",
				"venio-light": "#FFFFFF"
			}
		},
		{
			"key": "nav-icon-default",
			"cssVar": "--go5-nav-icon-default",
			"cls": null,
			"group": "other",
			"values": {
				"custom-light": "#FFFFFF",
				"empeo-dark": "#1C1C22",
				"empeo-light": "#FFFFFF",
				"etaxgo-light": "#FFFFFF",
				"salesbear-light": "#B5B5B5",
				"venio-dark": "#1C1C22",
				"venio-light": "#FFFFFF"
			}
		},
		{
			"key": "note-bg",
			"cssVar": "--go5-note-bg",
			"cls": null,
			"group": "other",
			"values": {
				"empeo-dark": "linear-gradient(0deg, rgba(0, 0, 0, 0.72) 0%, rgba(0, 0, 0, 0.72) 100%), #FFDC66",
				"empeo-light": "#FFFDF3",
				"etaxgo-light": "#FFFDF3",
				"salesbear-light": "#FFFDF3",
				"venio-dark": "linear-gradient(0deg, rgba(0, 0, 0, 0.72) 0%, rgba(0, 0, 0, 0.72) 100%), #FFDC66",
				"venio-light": "#FFFDF3"
			}
		},
		{
			"key": "note-border",
			"cssVar": "--go5-note-border",
			"cls": null,
			"group": "other",
			"values": {
				"empeo-dark": "#FFEAA3",
				"empeo-light": "#FFC505",
				"etaxgo-light": "#FFC505",
				"salesbear-light": "#FFC505",
				"venio-dark": "#FFEAA3",
				"venio-light": "#FFC505"
			}
		},
		{
			"key": "selection-active-bg",
			"cssVar": "--go5-selection-active-bg",
			"cls": null,
			"group": "other",
			"values": {
				"custom-light": "#F5F9FF",
				"empeo-dark": "linear-gradient(0deg, rgba(0, 0, 0, 0.72) 0%, rgba(0, 0, 0, 0.72) 100%), currentColor",
				"empeo-light": "#FFF3EC",
				"etaxgo-light": "#FFEAE5",
				"salesbear-light": "#FFF8E0",
				"venio-dark": "linear-gradient(0deg, rgba(0, 0, 0, 0.72) 0%, rgba(0, 0, 0, 0.72) 100%), currentColor",
				"venio-light": "#F5F9FF"
			}
		},
		{
			"key": "selection-default-bg",
			"cssVar": "--go5-selection-default-bg",
			"cls": null,
			"group": "other",
			"values": {
				"custom-light": "#FFFFFF",
				"empeo-dark": "#1C1C22",
				"empeo-light": "#FFFFFF",
				"etaxgo-light": "#FFFFFF",
				"salesbear-light": "#FFFFFF",
				"venio-dark": "#1C1C22",
				"venio-light": "#FFFFFF"
			}
		},
		{
			"key": "selection-default-line",
			"cssVar": "--go5-selection-default-line",
			"cls": null,
			"group": "other",
			"values": {
				"custom-light": "#D9D9D9",
				"empeo-dark": "#838395",
				"empeo-light": "#D2D2DA",
				"etaxgo-light": "#D2D2DA",
				"salesbear-light": "#D9D9D9",
				"venio-dark": "#838395",
				"venio-light": "#D9D9D9"
			}
		},
		{
			"key": "selection-default-text",
			"cssVar": "--go5-selection-default-text",
			"cls": null,
			"group": "other",
			"values": {
				"custom-light": "#838395",
				"empeo-dark": "#D2D2DA",
				"empeo-light": "#838395",
				"etaxgo-light": "#838395",
				"salesbear-light": "#838395",
				"venio-dark": "#D2D2DA",
				"venio-light": "#838395"
			}
		},
		{
			"key": "selection-disabled-bg",
			"cssVar": "--go5-selection-disabled-bg",
			"cls": null,
			"group": "other",
			"values": {
				"custom-light": "#F5F5F5",
				"empeo-dark": "#383842",
				"empeo-light": "#F6F6F8",
				"etaxgo-light": "#F6F6F8",
				"salesbear-light": "#F6F6F8",
				"venio-dark": "#383842",
				"venio-light": "#F6F6F8"
			}
		},
		{
			"key": "selection-disabled-line",
			"cssVar": "--go5-selection-disabled-line",
			"cls": null,
			"group": "other",
			"values": {
				"custom-light": "#D9D9D9",
				"empeo-dark": "#838395",
				"empeo-light": "#D2D2DA",
				"etaxgo-light": "#D2D2DA",
				"salesbear-light": "#D9D9D9",
				"venio-dark": "#838395",
				"venio-light": "#D9D9D9"
			}
		},
		{
			"key": "selection-disabled-text",
			"cssVar": "--go5-selection-disabled-text",
			"cls": null,
			"group": "other",
			"values": {
				"custom-light": "#D2D2DA",
				"empeo-dark": "#838395",
				"empeo-light": "#D2D2DA",
				"etaxgo-light": "#D2D2DA",
				"salesbear-light": "#D2D2DA",
				"venio-dark": "#838395",
				"venio-light": "#D2D2DA"
			}
		},
		{
			"key": "shadow-basic",
			"cssVar": "--go5-shadow-basic",
			"cls": null,
			"group": "shadow",
			"values": {
				"empeo-dark": "0 0 12px 0 rgba(255, 255, 255, 0.10)",
				"empeo-light": "0 0 12px 0 rgba(0, 0, 0, 0.10)",
				"etaxgo-light": "0 0 12px 0 rgba(0, 0, 0, 0.10)",
				"salesbear-light": "0 0 12px 0 rgba(0, 0, 0, 0.10)",
				"venio-dark": "0 0 12px 0 rgba(255, 255, 255, 0.10)",
				"venio-light": "0 0 12px 0 rgba(0, 0, 0, 0.10)"
			}
		},
		{
			"key": "shadow-highlight",
			"cssVar": "--go5-shadow-highlight",
			"cls": null,
			"group": "shadow",
			"values": {
				"empeo-dark": "0 2px 12px 0 rgba(255, 255, 255, 0.16)",
				"empeo-light": "0 2px 12px 0 rgba(0, 0, 0, 0.16)",
				"etaxgo-light": "0 2px 12px 0 rgba(0, 0, 0, 0.16)",
				"salesbear-light": "0 2px 12px 0 rgba(0, 0, 0, 0.16)",
				"venio-dark": "0 2px 12px 0 rgba(255, 255, 255, 0.16)",
				"venio-light": "0 2px 12px 0 rgba(0, 0, 0, 0.16)"
			}
		},
		{
			"key": "shadow-soft",
			"cssVar": "--go5-shadow-soft",
			"cls": null,
			"group": "shadow",
			"values": {
				"empeo-dark": "0 0 8px 0 rgba(255, 255, 255, 0.08)",
				"empeo-light": "0 0 8px 0 rgba(0, 0, 0, 0.08)",
				"etaxgo-light": "0 0 8px 0 rgba(0, 0, 0, 0.08)",
				"salesbear-light": "0 0 8px 0 rgba(0, 0, 0, 0.08)",
				"venio-dark": "0 0 8px 0 rgba(255, 255, 255, 0.08)",
				"venio-light": "0 0 8px 0 rgba(0, 0, 0, 0.08)"
			}
		},
		{
			"key": "table-body",
			"cssVar": "--go5-table-body",
			"cls": null,
			"group": "other",
			"values": {
				"custom-light": "#FFFFFF",
				"empeo-dark": "#1C1C22",
				"empeo-light": "#FFFFFF",
				"etaxgo-light": "#FFFFFF",
				"salesbear-light": "#FFFFFF",
				"venio-dark": "#1C1C22",
				"venio-light": "#FFFFFF"
			}
		},
		{
			"key": "table-header",
			"cssVar": "--go5-table-header",
			"cls": null,
			"group": "other",
			"values": {
				"custom-light": "#FFFFFF",
				"empeo-dark": "#ECECF1",
				"empeo-light": "#ECECF1",
				"etaxgo-light": "#FFFFFF",
				"salesbear-light": "#FFFFFF",
				"venio-dark": "#ECECF1",
				"venio-light": "#FFFFFF"
			}
		},
		{
			"key": "table-header-icon-sort",
			"cssVar": "--go5-table-header-icon-sort",
			"cls": null,
			"group": "other",
			"values": {
				"custom-light": "#FFFFFF99",
				"empeo-dark": "#FFFFFF99",
				"empeo-light": "#FFFFFF99",
				"etaxgo-light": "#FFFFFF99",
				"salesbear-light": "#6A6A7C",
				"venio-dark": "#FFFFFF99",
				"venio-light": "#FFFFFF99"
			}
		},
		{
			"key": "table-header-text",
			"cssVar": "--go5-table-header-text",
			"cls": null,
			"group": "other",
			"values": {
				"custom-light": "#FFFFFF",
				"empeo-dark": "#1C1C22",
				"empeo-light": "#FFFFFF",
				"etaxgo-light": "#FFFFFF",
				"salesbear-light": "#383842",
				"venio-dark": "#1C1C22",
				"venio-light": "#FFFFFF"
			}
		},
		{
			"key": "table-hover",
			"cssVar": "--go5-table-hover",
			"cls": null,
			"group": "other",
			"values": {
				"custom-light": "#F5F5F5",
				"empeo-dark": "#F6F6F8",
				"empeo-light": "#F6F6F8",
				"etaxgo-light": "#F6F6F8",
				"salesbear-light": "#F5F5F5",
				"venio-dark": "rgba(56, 56, 66, 0.6)",
				"venio-light": "#ECECF1"
			}
		},
		{
			"key": "table-hover-content-bg",
			"cssVar": "--go5-table-hover-content-bg",
			"cls": null,
			"group": "other",
			"values": {
				"custom-light": "#FAFAFB",
				"empeo-dark": "#2D2D35",
				"empeo-light": "#FAFAFB",
				"etaxgo-light": "#FAFAFB",
				"salesbear-light": "#FAFAFB",
				"venio-dark": "#2D2D35",
				"venio-light": "#FAFAFB"
			}
		},
		{
			"key": "table-line",
			"cssVar": "--go5-table-line",
			"cls": null,
			"group": "other",
			"values": {
				"custom-light": "#E2E2E2",
				"empeo-dark": "#6A6A7C",
				"empeo-light": "#E2E2E2",
				"etaxgo-light": "#E2E2E2",
				"salesbear-light": "#E2E2E2",
				"venio-dark": "#6A6A7C",
				"venio-light": "#E2E2E2"
			}
		},
		{
			"key": "tag-default-bg",
			"cssVar": "--go5-tag-default-bg",
			"cls": null,
			"group": "other",
			"values": {
				"custom-light": "#F5F9FF",
				"empeo-dark": "#F05B2F1A",
				"empeo-light": "#FFF3EC",
				"etaxgo-light": "#FFEAE5",
				"salesbear-light": "#FFF8E0",
				"venio-dark": "#1A2641",
				"venio-light": "#E7F0FF"
			}
		},
		{
			"key": "tag-hover",
			"cssVar": "--go5-tag-hover",
			"cls": null,
			"group": "other",
			"values": {
				"empeo-dark": "#072C65",
				"empeo-light": "#FFE1CC",
				"etaxgo-light": "#FFD8D1",
				"salesbear-light": "#FFF2C8",
				"venio-dark": "#072C65",
				"venio-light": "rgba(184, 211, 254, 0.60)"
			}
		},
		{
			"key": "text-color-1",
			"cssVar": "--go5-text-color-1",
			"cls": "go5-text-color-1",
			"group": "text",
			"values": {
				"custom-light": "#FFFFFF",
				"empeo-dark": "#1C1C22",
				"empeo-light": "#FFFFFF",
				"etaxgo-light": "#FFFFFF",
				"salesbear-light": "#FFFFFF",
				"venio-dark": "#1C1C22",
				"venio-light": "#FFFFFF"
			}
		},
		{
			"key": "text-color-10",
			"cssVar": "--go5-text-color-10",
			"cls": "go5-text-color-10",
			"group": "text",
			"values": {
				"custom-light": "#525260",
				"empeo-dark": "#ECECF1",
				"empeo-light": "#525260",
				"etaxgo-light": "#525260",
				"salesbear-light": "#525260",
				"venio-dark": "#ECECF1",
				"venio-light": "#525260"
			}
		},
		{
			"key": "text-color-11",
			"cssVar": "--go5-text-color-11",
			"cls": "go5-text-color-11",
			"group": "text",
			"values": {
				"custom-light": "#383842",
				"empeo-dark": "#F6F6F8",
				"empeo-light": "#383842",
				"etaxgo-light": "#383842",
				"salesbear-light": "#383842",
				"venio-dark": "#F6F6F8",
				"venio-light": "#383842"
			}
		},
		{
			"key": "text-color-12",
			"cssVar": "--go5-text-color-12",
			"cls": "go5-text-color-12",
			"group": "text",
			"values": {
				"custom-light": "#1C1C22",
				"empeo-dark": "#FFFFFF",
				"empeo-light": "#1C1C22",
				"etaxgo-light": "#1C1C22",
				"salesbear-light": "#1C1C22",
				"venio-dark": "#FFFFFF",
				"venio-light": "#1C1C22"
			}
		},
		{
			"key": "text-color-2",
			"cssVar": "--go5-text-color-2",
			"cls": "go5-text-color-2",
			"group": "text",
			"values": {
				"custom-light": "#F6F6F8",
				"empeo-dark": "#383842",
				"empeo-light": "#F6F6F8",
				"etaxgo-light": "#F6F6F8",
				"salesbear-light": "#F6F6F8",
				"venio-dark": "#383842",
				"venio-light": "#F6F6F8"
			}
		},
		{
			"key": "text-color-3",
			"cssVar": "--go5-text-color-3",
			"cls": "go5-text-color-3",
			"group": "text",
			"values": {
				"custom-light": "#ECECF1",
				"empeo-dark": "#525260",
				"empeo-light": "#ECECF1",
				"etaxgo-light": "#ECECF1",
				"salesbear-light": "#ECECF1",
				"venio-dark": "#525260",
				"venio-light": "#ECECF1"
			}
		},
		{
			"key": "text-color-4",
			"cssVar": "--go5-text-color-4",
			"cls": "go5-text-color-4",
			"group": "text",
			"values": {
				"custom-light": "#DFDFE8",
				"empeo-dark": "#6A6A7C",
				"empeo-light": "#DFDFE8",
				"etaxgo-light": "#DFDFE8",
				"salesbear-light": "#DFDFE8",
				"venio-dark": "#6A6A7C",
				"venio-light": "#DFDFE8"
			}
		},
		{
			"key": "text-color-5",
			"cssVar": "--go5-text-color-5",
			"cls": "go5-text-color-5",
			"group": "text",
			"values": {
				"custom-light": "#D2D2DA",
				"empeo-dark": "#838395",
				"empeo-light": "#D2D2DA",
				"etaxgo-light": "#D2D2DA",
				"salesbear-light": "#D2D2DA",
				"venio-dark": "#838395",
				"venio-light": "#D2D2DA"
			}
		},
		{
			"key": "text-color-6",
			"cssVar": "--go5-text-color-6",
			"cls": "go5-text-color-6",
			"group": "text",
			"values": {
				"custom-light": "#BCBCC8",
				"empeo-dark": "#A5A5B6",
				"empeo-light": "#BCBCC8",
				"etaxgo-light": "#BCBCC8",
				"salesbear-light": "#BCBCC8",
				"venio-dark": "#A5A5B6",
				"venio-light": "#BCBCC8"
			}
		},
		{
			"key": "text-color-7",
			"cssVar": "--go5-text-color-7",
			"cls": "go5-text-color-7",
			"group": "text",
			"values": {
				"custom-light": "#A5A5B6",
				"empeo-dark": "#BCBCC8",
				"empeo-light": "#A5A5B6",
				"etaxgo-light": "#A5A5B6",
				"salesbear-light": "#A5A5B6",
				"venio-dark": "#BCBCC8",
				"venio-light": "#A5A5B6"
			}
		},
		{
			"key": "text-color-8",
			"cssVar": "--go5-text-color-8",
			"cls": "go5-text-color-8",
			"group": "text",
			"values": {
				"custom-light": "#838395",
				"empeo-dark": "#D2D2DA",
				"empeo-light": "#838395",
				"etaxgo-light": "#838395",
				"salesbear-light": "#838395",
				"venio-dark": "#D2D2DA",
				"venio-light": "#838395"
			}
		},
		{
			"key": "text-color-9",
			"cssVar": "--go5-text-color-9",
			"cls": "go5-text-color-9",
			"group": "text",
			"values": {
				"custom-light": "#6A6A7C",
				"empeo-dark": "#DFDFE8",
				"empeo-light": "#6A6A7C",
				"etaxgo-light": "#6A6A7C",
				"salesbear-light": "#6A6A7C",
				"venio-dark": "#DFDFE8",
				"venio-light": "#6A6A7C"
			}
		},
		{
			"key": "feature-activity",
			"cssVar": null,
			"cls": "go5-color-feature-activity",
			"group": "feature",
			"values": {
				"custom-light": "#116DFC",
				"empeo-dark": "#116DFC",
				"empeo-light": "#116DFC",
				"etaxgo-light": "#116DFC",
				"salesbear-light": "#116DFC",
				"venio-dark": "#116DFC",
				"venio-light": "#116DFC"
			},
			"invalidHex": false
		},
		{
			"key": "feature-deal",
			"cssVar": null,
			"cls": "go5-color-feature-deal",
			"group": "feature",
			"values": {
				"custom-light": "#E00095",
				"empeo-dark": "#E00095",
				"empeo-light": "#E00095",
				"etaxgo-light": "#E00095",
				"salesbear-light": "#E00095",
				"venio-dark": "#E00095",
				"venio-light": "#E00095"
			},
			"invalidHex": false
		},
		{
			"key": "feature-case",
			"cssVar": null,
			"cls": "go5-color-feature-case",
			"group": "feature",
			"values": {
				"custom-light": "#FAC005",
				"empeo-dark": "#FAC005",
				"empeo-light": "#FAC005",
				"etaxgo-light": "#FAC005",
				"salesbear-light": "#FAC005",
				"venio-dark": "#FAC005",
				"venio-light": "#FAC005"
			},
			"invalidHex": false
		},
		{
			"key": "feature-customer",
			"cssVar": null,
			"cls": "go5-color-feature-customer",
			"group": "feature",
			"values": {
				"custom-light": "#4ca32",
				"empeo-dark": "#4ca32",
				"empeo-light": "#4ca32",
				"etaxgo-light": "#4ca32",
				"salesbear-light": "#4ca32",
				"venio-dark": "#4ca32",
				"venio-light": "#4ca32"
			},
			"invalidHex": true
		},
		{
			"key": "feature-quotation",
			"cssVar": null,
			"cls": "go5-color-feature-quotation",
			"group": "feature",
			"values": {
				"custom-light": "#7D2EF0",
				"empeo-dark": "#7D2EF0",
				"empeo-light": "#7D2EF0",
				"etaxgo-light": "#7D2EF0",
				"salesbear-light": "#7D2EF0",
				"venio-dark": "#7D2EF0",
				"venio-light": "#7D2EF0"
			},
			"invalidHex": false
		},
		{
			"key": "feature-salesorder",
			"cssVar": null,
			"cls": "go5-color-feature-salesorder",
			"group": "feature",
			"values": {
				"custom-light": "#116df",
				"empeo-dark": "#116df",
				"empeo-light": "#116df",
				"etaxgo-light": "#116df",
				"salesbear-light": "#116df",
				"venio-dark": "#116df",
				"venio-light": "#116df"
			},
			"invalidHex": true
		},
		{
			"key": "feature-expense",
			"cssVar": null,
			"cls": "go5-color-feature-expense",
			"group": "feature",
			"values": {
				"custom-light": "#3AA8AF",
				"empeo-dark": "#3AA8AF",
				"empeo-light": "#3AA8AF",
				"etaxgo-light": "#3AA8AF",
				"salesbear-light": "#3AA8AF",
				"venio-dark": "#3AA8AF",
				"venio-light": "#3AA8AF"
			},
			"invalidHex": false
		},
		{
			"key": "feature-conversation",
			"cssVar": null,
			"cls": "go5-color-feature-conversation",
			"group": "feature",
			"values": {
				"custom-light": "#116df",
				"empeo-dark": "#116df",
				"empeo-light": "#116df",
				"etaxgo-light": "#116df",
				"salesbear-light": "#116df",
				"venio-dark": "#116df",
				"venio-light": "#116df"
			},
			"invalidHex": true
		},
		{
			"key": "feature-contract",
			"cssVar": null,
			"cls": "go5-color-feature-contract",
			"group": "feature",
			"values": {
				"custom-light": "#0848AF",
				"empeo-dark": "#0848AF",
				"empeo-light": "#0848AF",
				"etaxgo-light": "#0848AF",
				"salesbear-light": "#0848AF",
				"venio-dark": "#0848AF",
				"venio-light": "#0848AF"
			},
			"invalidHex": false
		},
		{
			"key": "feature-task",
			"cssVar": null,
			"cls": "go5-color-feature-task",
			"group": "feature",
			"values": {
				"custom-light": "#116DFC",
				"empeo-dark": "#116DFC",
				"empeo-light": "#116DFC",
				"etaxgo-light": "#116DFC",
				"salesbear-light": "#116DFC",
				"venio-dark": "#116DFC",
				"venio-light": "#116DFC"
			},
			"invalidHex": false
		},
		{
			"key": "feature-warranty",
			"cssVar": null,
			"cls": "go5-color-feature-warranty",
			"group": "feature",
			"values": {
				"custom-light": "#116DFC",
				"empeo-dark": "#116DFC",
				"empeo-light": "#116DFC",
				"etaxgo-light": "#116DFC",
				"salesbear-light": "#116DFC",
				"venio-dark": "#116DFC",
				"venio-light": "#116DFC"
			},
			"invalidHex": false
		}
	]
};
