/**
 * Reads the Gofive design system's own theme sources and emits a typed token table.
 *
 * The values are NOT hand-copied on purpose: DS changes its palette between
 * releases, and a stale table is worse than no table at all — it answers
 * confidently and wrongly. Re-run this whenever the design system is bumped.
 *
 *   node scripts/extract-tokens.mjs [path-to-library-design-system]
 *
 * Sources it reads:
 *   projects/base/api/theme-*.ts                      → every theme's raw values
 *   projects/base/assets/styles/components/_text.scss → classes written literally
 *   projects/base/assets/styles/components/_color.scss→ classes built with @each
 */

import { readdir, readFile, writeFile } from "node:fs/promises";
import { execFileSync } from "node:child_process";
import { existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");

const dsRoot = resolve(process.argv[2] ?? join(repoRoot, "..", "library-design-system"));
const out = join(repoRoot, "src/shared/tokens.generated.ts");

const themeDir = join(dsRoot, "projects/base/api");
const textScssPath = join(dsRoot, "projects/base/assets/styles/components/_text.scss");
const colorScssPath = join(dsRoot, "projects/base/assets/styles/components/_color.scss");

for (const p of [themeDir, textScssPath, colorScssPath]) {
	if (!existsSync(p)) {
		console.error(`ไม่พบ ${p}`);
		console.error(`ส่ง path ของ library-design-system มาเป็น argument ตัวแรก`);
		process.exit(1);
	}
}

const HEX = /^#([0-9a-f]{3}|[0-9a-f]{6}|[0-9a-f]{8})$/i;

// ---- 1. every theme ----

const themes = {};
for (const file of (await readdir(themeDir)).filter((f) => /^theme-.*\.ts$/.test(f)).sort()) {
	const src = await readFile(join(themeDir, file), "utf8");
	const name = file.replace(/^theme-|\.ts$/g, "");
	const map = {};
	for (const m of src.matchAll(/['"]([a-z0-9-]+)['"]\s*:\s*['"]([^'"]+)['"]/gi)) map[m[1]] = m[2];
	themes[name] = map;
}

/** `'button-primary-default-bg': 'var(--go5-color-primary)'` has to be chased to a real value. */
function resolveValue(theme, value, depth = 0) {
	if (depth > 8 || typeof value !== "string") return value;
	const m = value.match(/^var\(\s*--go5-([a-z0-9-]+)\s*\)$/i);
	if (!m) return value;
	const next = themes[theme][m[1]];
	return next === undefined ? value : resolveValue(theme, next, depth + 1);
}

// ---- 2. which tokens actually have a utility class ----

const textScss = await readFile(textScssPath, "utf8");
const colorScss = await readFile(colorScssPath, "utf8");

const literalClasses = new Set((textScss.match(/\.go5-[a-z0-9-]+/g) ?? []).map((s) => s.slice(1)));

// `.go5-color-primary` and friends are generated by @each, so grepping the
// literal string finds nothing even though the class is real.
const eachColors = (colorScss.match(/^\$colors:\s*(.+);/m)?.[1] ?? "")
	.split(",")
	.map((s) => s.trim().replace(/['"]/g, ""))
	.filter(Boolean);

const featureBlock = colorScss.match(/\$features:\s*\(([\s\S]*?)\n\);/)?.[1] ?? "";
const features = [...featureBlock.matchAll(/([a-z0-9-]+):\s*\(\s*color:\s*([^,\n]+),?/gi)].map((m) => ({
	key: m[1],
	raw: m[2].trim().replace(/['"]/g, ""),
}));

// ---- 3. shape it ----

function groupOf(key) {
	if (/^text-color-/.test(key)) return "text";
	if (/^shadow-/.test(key)) return "shadow";
	if (/^color-(primary|secondary|success|error|warning|loading)/.test(key)) return "semantic";
	if (/^bg-/.test(key)) return "surface";
	if (/^button-/.test(key)) return "button";
	if (/^(input|form|field|textfield)/.test(key)) return "input";
	return "other";
}

const themeNames = Object.keys(themes).sort();
const allKeys = [...new Set(themeNames.flatMap((t) => Object.keys(themes[t])))].sort();

const rows = allKeys.map((key) => {
	const values = {};
	for (const t of themeNames) {
		const raw = themes[t][key];
		if (raw === undefined) continue;
		const resolved = resolveValue(t, raw);
		values[t] = HEX.test(resolved) ? resolved.toUpperCase() : resolved;
	}

	let cls = null;
	if (literalClasses.has(`go5-${key}`)) cls = `go5-${key}`;
	if (key.startsWith("color-") && eachColors.includes(key.replace(/^color-/, ""))) cls = `go5-${key}`;

	return { key, cssVar: `--go5-${key}`, cls, group: groupOf(key), values };
});

// Feature colours are hardcoded in SCSS, identical in every theme.
for (const f of features) {
	const hex = HEX.test(f.raw) ? f.raw.toUpperCase() : f.raw;
	rows.push({
		key: `feature-${f.key}`,
		cssVar: null,
		cls: `go5-color-feature-${f.key}`,
		group: "feature",
		values: Object.fromEntries(themeNames.map((t) => [t, hex])),
		invalidHex: !HEX.test(f.raw),
	});
}

// ---- 4. write ----

/**
 * Without this stamp there is no way to tell later which state of the design
 * system a given snapshot came from — a value that looks wrong cannot be traced
 * back to a commit, so you cannot tell a DS change from a bad extraction.
 */
function dsRevision() {
	try {
		const at = (args) => execFileSync("git", ["-C", dsRoot, ...args], { encoding: "utf8" }).trim();
		return `${at(["rev-parse", "--short", "HEAD"])} · ${at(["log", "-1", "--date=short", "--format=%ad"])} · ${at(["rev-parse", "--abbrev-ref", "HEAD"])}`;
	} catch {
		return "unknown (not a git checkout)";
	}
}

const revision = dsRevision();

const banner = `// GENERATED by scripts/extract-tokens.mjs — do not edit by hand.
// Source:   ${dsRoot.replace(process.env.HOME ?? "", "~")}
// Revision: ${revision}
// Re-run \`npm run tokens\` after the design system changes, then \`npm run build\`.
`;

const body = `import type { TokenTable } from "./tokens.ts";

export const TOKENS: TokenTable = ${JSON.stringify({ themes: themeNames, rows }, null, "\t")};
`;

await writeFile(out, `${banner}\n${body}`, "utf8");

// ---- 5. report ----

const withClass = rows.filter((r) => r.cls).length;
const broken = rows.filter((r) => r.invalidHex);
const byGroup = {};
for (const r of rows) byGroup[r.group] = (byGroup[r.group] ?? 0) + 1;

console.log(`เขียน ${out.replace(repoRoot + "/", "")}`);
console.log(`  DS         ${revision}`);
console.log(`  ธีม        ${themeNames.length} · ${themeNames.join(", ")}`);
console.log(`  token      ${rows.length} (มี utility class ${withClass})`);
console.log(
	`  กลุ่ม      ${Object.entries(byGroup)
		.sort()
		.map(([k, v]) => `${k}:${v}`)
		.join(" ")}`,
);

if (broken.length) {
	console.warn(`\n  ⚠ hex ไม่ถูกต้องใน DS ${broken.length} รายการ — CSS จะทิ้ง declaration ทั้งบรรทัด`);
	for (const b of broken) console.warn(`     .${b.cls} = ${b.values[themeNames[0]]}`);
}